// TypeScript types for Section 3 compliance data models

export interface Contract {
  id: string
  contractNumber: string
  contractName: string
  contractorId: string
  projectId: string
  contractType: "construction" | "rehabilitation" | "public_construction" | "lead_hazard_control" | "other"
  contractValue: number
  startDate: string
  endDate: string | null
  status: "draft" | "active" | "completed" | "terminated" | "suspended"
  hudFundingAmount: number
  totalProjectCost: number
  fundingSourceId: string | null
  section3Applicable: boolean
  applicabilitySubpart: "Subpart B" | "Subpart C" | "N/A"
  applicabilityThreshold: number | null
  applicabilityReason: string | null
  applicabilityCalculatedAt: string | null
  laborHourBenchmark: number | null
  targetedSection3Benchmark: number | null
  contractDocumentUrl: string | null
  signedContractUrl: string | null
  createdBy: string | null
  createdAt: string
  updatedAt: string
}

export interface FundingSource {
  id: string
  sourceName: string
  sourceType: string
  hudProgramCode: string | null
  defaultThreshold: number
  requiresSection3: boolean
  subpartType: "Subpart B" | "Subpart C"
  description: string | null
  isActive: boolean
  createdAt: string
  updatedAt: string
}

export interface ComplianceForm {
  id: string
  contractId: string
  formType: "quarterly" | "annual" | "final" | "ad_hoc"
  reportingPeriodStart: string
  reportingPeriodEnd: string
  dueDate: string
  status: "pending" | "in_progress" | "submitted" | "approved" | "rejected"
  submittedAt: string | null
  submittedBy: string | null
  approvedAt: string | null
  approvedBy: string | null
  totalLaborHours: number
  section3LaborHours: number
  targetedSection3Hours: number
  complianceRate: number | null
  targetedComplianceRate: number | null
  outreachEfforts: string | null
  trainingProvided: string | null
  challengesEncountered: string | null
  successStories: string | null
  formDocumentUrl: string | null
  supportingDocuments: string[]
  createdAt: string
  updatedAt: string
}

export interface Benchmark {
  id: string
  contractId: string
  benchmarkType: "labor_hours" | "targeted_hours" | "contracting" | "custom"
  benchmarkName: string
  targetPercentage: number | null
  targetAbsoluteValue: number | null
  measurementUnit: string | null
  currentValue: number
  currentPercentage: number
  isMet: boolean
  periodStart: string
  periodEnd: string
  description: string | null
  createdAt: string
  updatedAt: string
}

export interface Task {
  id: string
  contractId: string
  complianceFormId: string | null
  taskType:
    | "report_submission"
    | "worker_verification"
    | "document_upload"
    | "training"
    | "outreach"
    | "audit"
    | "custom"
  title: string
  description: string | null
  assignedTo: string | null
  assignedBy: string | null
  status: "pending" | "in_progress" | "completed" | "overdue" | "cancelled"
  priority: "low" | "medium" | "high" | "urgent"
  dueDate: string
  reminderDate: string | null
  completedAt: string | null
  isAutoGenerated: boolean
  autoGenerationRule: string | null
  createdAt: string
  updatedAt: string
}

export interface ContractLaborSummary {
  id: string
  contractId: string
  summaryPeriod: "daily" | "weekly" | "monthly" | "quarterly" | "annual" | "total"
  periodStart: string
  periodEnd: string
  totalHours: number
  section3Hours: number
  targetedSection3Hours: number
  totalWorkers: number
  section3Workers: number
  targetedSection3Workers: number
  section3ComplianceRate: number | null
  targetedComplianceRate: number | null
  meetsSection3Benchmark: boolean
  meetsTargetedBenchmark: boolean
  lastCalculatedAt: string
  createdAt: string
  updatedAt: string
}
